server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shopaholism/priceFlow-config.git
          username: parkchanbin54
          password: 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
          default-label: main
          ignore-local-ssh-settings: true
